# 📦 PromptOps Lifecycle Governance - Root Configuration File

# This file unifies schema, evaluation, logging, and CI references
# Used for orchestration, tool integration, and CI workflows

promptops:
  name: "PromptOps Governance Scaffold"
  version: "1.0.0"
  environment: "staging"
  created_by: "Hou Chia"

paths:
  prompt_cards:
    canonical: "schemas/prompt-card.example.yml"
    dashboard: "schemas/prompt-card.dashboard.yml"
  prompt_versions:
    prod: "schemas/prompt-version.prod-approved.yml"
  evals:
    base: "evals/eval-config.promptfoo.yml"
    variant: "evals/eval-config.variant.promptfoo.yml"
    compare: "evals/eval-config.compare.promptfoo.yml"
    rag: "evals/eval-config.rag.promptfoo.yml"
  test_cases:
    base: "evals/test-cases.json"
    variants: "evals/test-cases.variant.json"
    rag: "evals/test-cases.rag.json"
  logs:
    schema: "logs/prompt-log-schema.json"
    sample: "logs/log-sample.output.json"
  reports:
    rag_eval: "evals/eval-report.rag.md"
  ci:
    gating: "ci/ci-prod-block.yml"
  workflows:
    approval: "workflows/HITL_Approval_Template.md"
    promotion: "workflows/promotion-pipeline.md"

tooling:
  dashboard_generator: "scripts/generate-dashboard-card.py"
  eval_runner: "scripts/prompt-eval-runner.py"

defaults:
  eval_threshold:
    score: 0.85
    pass_rate: 0.90
  rollback_conditions:
    - "Fails hallucination eval in CI"
    - "Cost spike > 20% vs. baseline"
    - "Retrieval success rate < 80%"

license: "MIT (contact for commercial use)"
