name: promptops-variant-test
model: anthropic:claude-3-opus
tests:
  - path: evals/test-cases.variant.json
assertions:
  - type: includes
    value: User
  - type: not_empty
  - type: metadata
    key: cost_usd
    operator: <=
    value: 0.01
